### ISSUE TITLE
Query weather.mios.com (& Virtual Outdoor Temperature Plugin)

### ISSUE THREAD

**Issue by tunnus-1** [toggledbits/Vera-Decouple#3]
@toggledbits, could you make this a configurable item ( #1 )? I would like to retain this functionality with decoupled Vera, as I'm using Virtual Outdoor Temperature Plugin. It's also nice to have weather info & icon on the UI. 

Is re-enabling weather.mios.com queries as easy as removing a line "server=/weather.mios.com/" from /var/etc/dnsmasq.conf?

**Comment by dbochicchio** [comment]
Weather and apps.mios.com are whitelisted in the latest version. In fact, I'm OK with both weather in the UI, as well as the app store.

**Comment by tunnus-1** [comment]
> Weather and apps.mios.com are whitelisted in the latest version. In fact, I'm OK with both weather in the UI, as well as the app store.

I have the latest version, but still weather info & VOTS plugin are not working as they were without decouple

**Comment by toggledbits** [comment]
Update 20347; new config variable `KEEP_MIOS_WEATHER` can be set to preserve the weather service feed.

**Comment by toggledbits** [comment]
I'm re-opening this. Someone (tomtcom) commented in a forum post that VOTS uses Yahoo weather, suggesting to me it's not Vera's cloud and the setting/capability here isn't relevant/necessary.

To be clear: decoupling from the cloud using these scripts decouples from the *Vera* cloud. There is nothing to prevent you from using any other cloud services. Your cloud-based plugins will continue to work. It is only Vera's native services that are decoupled and blocked. Was this not understood prior to making this request?

**Comment by tunnus-1** [comment]
Yes it was understood, that's why it was suprising VOTS stopped working. Apparently VOTS and the "basic" weather info in the upper right corner of the UI7 are using the same mechanism for weather updates as after this fix (KEEP_MIOS_WEATHER=1) *both* started working again. 

Thanks for the fix!

**Comment by toggledbits** [comment]
It's a plugin they wrote, so I'm not surprised... "why go to Yahoo's infrastructure directly when you go through our less-capable cloud?" Awesome.

**Comment by toggledbits** [comment]
And I just installed the plugin and look at its code, sure enough, it uses weather.mios.com instead of going to Yahoo directly. So that's confirmed by code as well as observation. 

As alternatives, there's also SiteSensor's published recipes for OpenWeatherMap, US National Weather Service, Swedish Weather, and Australia Weather. All free.

**Comment by tunnus-1** [comment]
ok
